import { loadGetInitialProps } from 'next/dist/next-server/lib/utils'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tech2Day</title>
        <meta name="viewport" content="width-device-width, initial-scale=1,maximum-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
      </Head>
      <body>
        <input type="checkbox" id="navtoggle" className={styles.navtoggle} />
      <div className={styles.dash}>
      <div className={styles.logo}>
          <img src="/logo.png" />
        </div>
      
        <ul>
          <li><a href="#" className={styles.active}><span class="fas fa-igloo"></span><span>Dashboard</span></a></li>
          <li><a href="#"><span class="fas fa-users"></span><span>Customers</span></a></li>
          <li><a href="#"><span class="fas fa-clipboard-list"></span><span>Projects</span></a></li>
          <li><a href="#"><span class="fas fa-shopping-bag"></span><span>Orders</span></a></li>
          <li><a href="#"><span class="fas fa-receipt"></span><span>Inventory</span></a></li>
          <li><a href="#"><span class="fas fa-user-circle"></span><span>Accounts</span></a></li>
          <li><a href="#"><span class="fas fa-tasks"></span><span>Tasks</span></a></li>
        </ul>
      </div>
    <div className={styles.maincontent}>
      <header className={styles.headerone}>
      <h2>
        <label for="navtoggle" className={styles.navtoggle}>
        <span class="fas fa-bars"></span></label>Dashboard</h2>

        <div className={styles.searchwrapper}>
        <span class="fas fa-search"></span>
        <input type="search" placeholder="Search Here" />
        </div>
    
        <div className={styles.userwrapper}>
        <img src="/manonpc.png" width="50px" height="50px"/>
        <div>
          <h4>Faizan Habib</h4>
          <small>Super Admin</small>
          </div>
        </div>
        </header>
        <main className={styles.main}>

          <div className={styles.cards}>
          <div className={styles.cardsingle}>
            <div>
              <h1>54</h1>
            <span>Customers</span>
            </div>
          <div>
            <span class="fas fa-users"></span>
          </div>
          </div>
          <div className={styles.cardsingle}>
            <div>
              <h1>79</h1>
            <span>Projects</span>
            </div>
          <div>
            <span class="fas fa-clipboard-list"></span>
          </div>
          </div>
          <div className={styles.cardsingle}>
            <div>
              <h1>124</h1>
            <span>Orders</span>
            </div>
          <div>
            <span class="fas fa-shopping-bag"></span>
          </div>
          </div>
          <div className={styles.cardsingle}>
            <div>
              <h1>$6k</h1>
            <span>Income</span>
            </div>
          <div>
            <span class="fab fa-google-wallet"></span>
          </div>
          </div>


          </div>
    <div className={styles.recentgrid}>
      <div className={styles.projects}>
        <div className={styles.card}>
          <div className={styles.cardheader}>
            <h3>Recent Projects</h3>
            <button>See All <span class="fas fa-arrow-right"></span></button>
          </div>
          <div className={styles.cardbody}>
            <div className={styles.tableresponsive}>
            <table className={styles.table} width="100%">
              <thead className={styles.thead}>
                <tr className={styles.tr}>
                  <td className={styles.td}>Project Title</td>
                  <td className={styles.td}>Department</td>
                  <td className={styles.td}>Status</td>
                </tr>
              </thead>
              <tbody className={styles.tbody}>
                <tr className={styles.tr}>
                  <td className={styles.td}>UI/UX Design</td>
                  <td className={styles.td}>UI Team</td>
                  <td className={styles.td}><span className={styles.status}> Review </span></td>
                </tr>
                <tr className={styles.tr}>
                  <td className={styles.td}>Web Development</td>
                  <td className={styles.td}>Frontend</td>
                  <td className={styles.td}><span className={styles.status}> in Progress </span></td>
                </tr>
                <tr className={styles.tr}>
                  <td className={styles.td}>Ushop App</td>
                  <td className={styles.td}>Mobile Team</td>
                  <td className={styles.td}><span className={styles.status}> Pending </span></td>
                </tr>
                <tr className={styles.tr}>
                  <td className={styles.td}>UI/UX Design</td>
                  <td className={styles.td}>UI Team</td>
                  <td className={styles.td}><span className={styles.status}> Review </span></td>
                </tr>
                <tr className={styles.tr}>
                  <td className={styles.td}>Web Development</td>
                  <td className={styles.td}>Frontend</td>
                  <td className={styles.td}><span className={styles.status}> in Progress </span></td>
                </tr>
                <tr className={styles.tr}>
                  <td className={styles.td}>Ushop App</td>
                  <td className={styles.td}>Mobile Team</td>
                  <td className={styles.td}><span className={styles.status}> Pending </span></td>
                </tr>
              </tbody>
            </table>
          </div>
          </div>
        </div>
      </div>
      <div className={styles.customers}>
        <div className={styles.card}>
          <div className={styles.cardheader}>
            <h3>New Customer</h3>
            <button>See All <span class="fas fa-arrow-right"></span></button>
          </div>
          <div className={styles.cardbody}>
              <div className={styles.customer}>
                <div className={styles.info}>
                <img src="/manonpc.png" width="50px" height="50px"/>
                <div>
                  <h4>Lewis S</h4>
                  <small>CEO Excerp</small>
                </div>
                </div>
                <div className={styles.contact}>
                  <span class="fas fa-user-circle"></span>
                  <span class="fas fa-comment"></span>
                  <span class="fas fa-phone"></span>
                </div>
              </div>
              <div className={styles.customer}>
                <div className={styles.info}>
                <img src="/manonpc.png" width="50px" height="50px"/>
                <div>
                  <h4>Lewis S</h4>
                  <small>CEO Excerp</small>
                </div>
                </div>
                <div className={styles.contact}>
                  <span class="fas fa-user-circle"></span>
                  <span class="fas fa-comment"></span>
                  <span class="fas fa-phone"></span>
                </div>
              </div>
              <div className={styles.customer}>
                <div className={styles.info}>
                <img src="/manonpc.png" width="50px" height="50px"/>
                <div>
                  <h4>Lewis S</h4>
                  <small>CEO Excerp</small>
                </div>
                </div>
                <div className={styles.contact}>
                  <span class="fas fa-user-circle"></span>
                  <span class="fas fa-comment"></span>
                  <span class="fas fa-phone"></span>
                </div>
              </div>
              <div className={styles.customer}>
                <div className={styles.info}>
                <img src="/manonpc.png" width="50px" height="50px"/>
                <div>
                  <h4>Lewis S</h4>
                  <small>CEO Excerp</small>
                </div>
                </div>
                <div className={styles.contact}>
                  <span class="fas fa-user-circle"></span>
                  <span class="fas fa-comment"></span>
                  <span class="fas fa-phone"></span>
                </div>
              </div>
              <div className={styles.customer}>
                <div className={styles.info}>
                <img src="/manonpc.png" width="50px" height="50px"/>
                <div>
                  <h4>Lewis S</h4>
                  <small>CEO Excerp</small>
                </div>
                </div>
                <div className={styles.contact}>
                  <span class="fas fa-user-circle"></span>
                  <span class="fas fa-comment"></span>
                  <span class="fas fa-phone"></span>
                </div>
              </div>
          </div>
        </div>
    </div>
      </div>
        </main>


    
    </div>
    </body>
    </div>
  )
}
